server:
  port: 10000

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
#    com.zaxxer.hikari: DEBUG

discord:
  token: ${DISCORD_TOKEN}
  channelName: test
spring:
  application:
    name: AnifAdmin
  data:
    mongodb:
      host: ${ANIF_ADMIN_HOST}
      port: ${ANIF_ADMIN_PORT}
      authentication-database: admin
      database: ${ANIF_ADMIN_DATABASE}
      username: ${ANIF_ADMIN_USERNAME}
      password: ${ANIF_ADMIN_PASSWORD}

  #log
  output:
    ansi:
      enabled: always

  devtools:
    livereload:
      enabled: false